import streamlit as st
import requests
st.set_page_config(page_title="AI Text Detector", layout="centered")
st.title("🕵️ AI-Generated Text Detector")
st.write("Enter a piece of text and we'll try to detect if it was written by a human or generated by AI (GPT-2 level).")

# Input text
user_input = st.text_area("Enter text here:", height=200)

if st.button("Detect"):
    if not user_input.strip():
        st.warning(" Please Enter the input...")
    else:
        with st.spinner("Detecting..."):
            try:  
                response = requests.post("http://127.0.0.1:5000/test",json={"text":user_input})
                result=response.json()
                if response.status_code==200:
                    label = result["label"]
                    score = result["score"]
                    if label == "REAL":
                            st.success(f"🧠 Human-written text (Confidence: {score:.2%})")
                    else:
                            st.error(f"🤖 AI-generated text (Confidence: {score:.2%})")
            
                else:
                    st.error("Error: Unable to process the request.")

            except requests.exceptions.RequestException as e:
                st.error(f"Error: {e}")